CREATE TABLE AREA (
  idArea INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY(idArea)
);

CREATE TABLE CARGO (
  idCargo INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  PRIMARY KEY(idCargo)
);

CREATE TABLE CURSO (
  idCurso INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AREA_idArea INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  oferta VARCHAR(50) NOT NULL,
  periodo VARCHAR(50) NOT NULL,
  cargaHoraria INTEGER UNSIGNED NOT NULL,
  horasDias TIME NOT NULL,
  qtdAlunos INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idCurso),
  INDEX CURSOS_FKIndex1(AREA_idArea)
);

CREATE TABLE EQUIPAMENTO (
  idEquipamento INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AREA_idArea INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  quantidade INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idEquipamento),
  INDEX EQUIPAMENTOS_FKIndex1(AREA_idArea)
);

CREATE TABLE LOGIN (
  idLogin INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PESSOA_idPessoa INTEGER UNSIGNED NOT NULL,
  nivelAcesso ENUM(2) NOT NULL DEFAULT user,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  PRIMARY KEY(idLogin),
  INDEX LOGIN_FKIndex1(PESSOA_idPessoa)
);

CREATE TABLE OCUPADO (
  qtdOcupado INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EQUIPAMENTO_idEquipamento INTEGER UNSIGNED NOT NULL,
  RESERVA_idReserva INTEGER UNSIGNED NOT NULL,
  INDEX OCUPADO_FKIndex1(RESERVA_idReserva),
  INDEX OCUPADO_FKIndex2(EQUIPAMENTO_idEquipamento)
);

CREATE TABLE PESSOA (
  idPessoa INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CARGO_idCargo INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(255) NOT NULL,
  CPF_CNPJ VARCHAR(18) NOT NULL,
  nascimento DATE NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY(idPessoa),
  INDEX PESSOA_FKIndex1(CARGO_idCargo)
);

CREATE TABLE PREDIO (
  idPredio INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(85) NOT NULL,
  PRIMARY KEY(idPredio)
);

CREATE TABLE RESERVA (
  idReserva INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PESSOA_idPessoa INTEGER UNSIGNED NOT NULL,
  CURSO_idCurso INTEGER UNSIGNED NOT NULL,
  LOGIN_idLogin INTEGER UNSIGNED NOT NULL,
  SALA_idSala INTEGER UNSIGNED NOT NULL,
  dia DATE NOT NULL,
  hrInicio TIME NOT NULL,
  hrFim TIME NOT NULL,
  observacao VARCHAR(255) NULL,
  PRIMARY KEY(idReserva),
  INDEX RESERVAS_FKIndex2(SALA_idSala),
  INDEX RESERVAS_FKIndex4(CURSO_idCurso),
  INDEX RESERVAS_FKIndex5(PESSOA_idPessoa),
  INDEX RESERVAS_FKIndex5(LOGIN_idLogin)
);

CREATE TABLE SALA (
  idSala INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO_SALA_idTipoSala INTEGER UNSIGNED NOT NULL,
  PREDIO_idPredio INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(50) NOT NULL,
  equipamentos VARCHAR(255) NOT NULL,
  capacidade INTEGER UNSIGNED NOT NULL,
  observacao VARCHAR(255) NULL,
  PRIMARY KEY(idSala),
  INDEX SALA_FKIndex1(PREDIO_idPredio),
  INDEX SALA_FKIndex2(TIPO_SALA_idTipoSala)
);

CREATE TABLE TIPO_SALA (
  idTipoSala INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  PRIMARY KEY(idTipoSala)
);


