CREATE TABLE AREA (
  idArea INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY(idArea)
);

CREATE TABLE CURSOS (
  idCursos INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AREA_idArea INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  oferta VARCHAR(50) NOT NULL,
  periodo VARCHAR(50) NOT NULL,
  cargaHoraria INTEGER UNSIGNED NOT NULL,
  horasDias TIME NOT NULL,
  qtdAlunos INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idCursos),
  INDEX CURSOS_FKIndex1(AREA_idArea)
);

CREATE TABLE EQUIPAMENTOS (
  idEquipamentos INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AREA_idArea INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  quantidade INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idEquipamentos),
  INDEX EQUIPAMENTOS_FKIndex1(AREA_idArea)
);

CREATE TABLE LOGIN (
  idLogin INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PESSOAS_idPessoas INTEGER UNSIGNED NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(100) NOT NULL,
  PRIMARY KEY(idLogin),
  INDEX LOGIN_FKIndex1(PESSOAS_idPessoas)
);

CREATE TABLE PESSOAS (
  idPessoas INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  CPF_CNPJ VARCHAR(18) NOT NULL,
  nascimento DATE NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  email VARCHAR(100) NOT NULL,
  cargo VARCHAR(50) NOT NULL,
  PRIMARY KEY(idPessoas)
);

CREATE TABLE RESERVAS (
  idReserva INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EQUIPAMENTOS_idEquipamentos INTEGER UNSIGNED NULL,
  LOGIN_idLogin INTEGER UNSIGNED NOT NULL,
  PESSOAS_idPessoas INTEGER UNSIGNED NOT NULL,
  CURSOS_idCursos INTEGER UNSIGNED NOT NULL,
  SALA_idSala INTEGER UNSIGNED NOT NULL,
  dia DATE NOT NULL,
  hrInicio TIME NOT NULL,
  hrFim TIME NOT NULL,
  observacoes VARCHAR(255) NULL,
  PRIMARY KEY(idReserva),
  INDEX RESERVAS_FKIndex2(SALA_idSala),
  INDEX RESERVAS_FKIndex4(CURSOS_idCursos),
  INDEX RESERVAS_FKIndex5(PESSOAS_idPessoas),
  INDEX RESERVAS_FKIndex5(LOGIN_idLogin),
  INDEX RESERVAS_FKIndex5(EQUIPAMENTOS_idEquipamentos)
);

CREATE TABLE SALA (
  idSala INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  predio VARCHAR(10) NOT NULL,
  equipamentos VARCHAR(255) NOT NULL,
  capacidade INTEGER UNSIGNED NOT NULL,
  observacoes VARCHAR(255) NULL,
  PRIMARY KEY(idSala)
);


